name: cesarcrypt
description: Caesar encryption CLI and Lib
version: 1.0.0
# homepage: https://github.com/Jalkhov/cesarcrypt

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  tabular: ^0.6.3+1
